### PR TITLE
Replace django-chartit with django-chartit2

### PR DESCRIPTION
**Pull request by rubik**
Submitting as a separate PR since it does not really have anything to do with datetimes.

### CODE REVIEW

**Comment by owocki** [comment]
Seems fine to me.  Anyone else?

**Comment by igorpejic** [comment]
We should probably remove these ugly fixes from the package source codes specific for django chartit:
https://github.com/owocki/pytrader/blob/256f6804126c85a7ebf3f89e457a22c1927b5fb3/Dockerfile#L26 https://github.com/owocki/pytrader/blob/256f6804126c85a7ebf3f89e457a22c1927b5fb3/docker/wait-and-run.sh#L16

**Comment by rubik** [comment]
Yeah, that's no longer necessary. I'll update the PR.

**Comment by rubik** [comment]
Done.

**Comment by owocki** [comment]
I'm good with merge here.  @igorpejic @Snipa22 @t0mk ?

**Comment by owocki** [comment]
seeing merge conflicts here.  can you rebase or pull owocki/master into your branch so i can merge?

**Comment by rubik** [comment]
Sure, done.

**Pull request merged**
