### PR TITLE
Purge historical development migrations and generate a fresh new initial one

### PR DESCRIPTION
**Pull request by richardpetithory**
Addresses #12

### CODE REVIEW

**Comment by owocki** [comment]
:+1: thanks richard, i should have checked this before i posted the code

**Comment by richardpetithory** [comment]
Glad to help. Most of the sciency stuff in this project is over my head, but I'm interested in learning, so I figure I can at least help with some of the pythonish stuff.

**Comment by owocki** [comment]
> Glad to help. Most of the sciency stuff in this project is over my head

You and me both brother.   This project is a practical way for me to learn/test ML stuff as much as it is an attempt to make some profit.  You'll notice that [in the prediction management commands](https://github.com/owocki/pytrader/blob/master/history/management/commands/predict_many_sk.py#L11-L26) that I'm enumerating a lot of parameters to try and find a classifier that will predict price movements.  This is admittedly a pretty brute force way of approaching the problem, but it's yielded some promising results so far. If a ML expert were to start contributing, that surely would help a lot.

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.1 ETH (69.21 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/owocki/pytrader/15/480).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Pull request merged**
