### PR TITLE
Websockets

### PR DESCRIPTION
**Pull request by Snipa22**
Websocket support for poloinex.  Generic enough that we should be able to add more easily, also leaves space in case we want to track trades.

Running from master with fetch and merge cleanly.  Daemonized like trade, dockers are setup to auto-run, so they can comment out the run requirement in cronjobs!

### CODE REVIEW

**Comment by owocki** [comment]
code looks good.   my only comment is:  would it be a good move to allow some rate limiting on the DB writes?  i doubt trade.py (or any future trader) is ever going to need more than 1 data ticker per minute.  we incur a performance penalty with any write; and i'm not concerned primarily with the initial write, as i am about the cumulative weight of the table over time.

**Comment by Snipa22** [comment]
As for rate-limiting, I did consider that, I've been considering how best to handle things like this.

I personally, like as much data as I can get, as I tend to find more data gives me more things to play with.  I did consider that in the car this morning, and I'll put in a rate-limiter later today, I've figured out how I'd like to do it.

**Comment by owocki** [comment]
I agree that rate limiting is a highly personal decision, depending on a lot of factors -- For me, my hardware/network wouldnt support a ton more than 1 data point per minute nor would I have any use for sub-minute price data.  Maybe the solutions is a `settings.py` entry that can be overriden, but defaults to 'unlimited' ?

**Comment by Snipa22** [comment]
My thought was going to be set it to 60 seconds (Current cron), then reduce in local_settings.py, but it would default to 60 seconds.  The reason is that we can setup a TDelta with that stored, then do a comparison with the last saved time, etc.

**Comment by owocki** [comment]
@Snipa22 let me know if you'd like to add the rate limiter as part of this PR or as an addition in another PR.  

if the latter, i think this is ready to :ship:  if not, maybe we should close this PR until the addition is added.

cc @t0mk

**Comment by Snipa22** [comment]
I'll add the rate limiter tonight, then it should be good to go.  I'll ping you when it's ready.

**Comment by Snipa22** [comment]
I'll rebase and resubmit this.  The merge did not clean up properly as my local repo got borked.

**Pull request closed without merging**
