### PR TITLE
travis ci with flake8

### PR DESCRIPTION
**Pull request by igorpejic**
#63 

Pep8ify code and configure continuous check with Travis CI (thanks @t0mk for template).
Max-line-length set at 120.

### CODE REVIEW

**Comment by owocki** [comment]
awesome!  this gets everything on to the same page WRT to styling :)

will hopefully have time to take a deeper look tonight

**Comment by t0mk** [comment]
Looks good - both the .travis and the lints. Next time please put Travis integration and style fixes in 2 different PRs.

**Comment by owocki** [comment]
> Next time please put 2 different things like Travis integration and style fixes in 2 different PRs.

This is my fault, I set a bad precedent by using my linter inconsistently. :P

**Comment by owocki** [comment]
Any objections to :ship: ing this @Snipa22 @t0mk ?

**Comment by owocki** [comment]
closing due to https://github.com/owocki/pytrader/pull/72

**Pull request closed without merging**
