### PR TITLE
Moves NN / classifier trainers & trader information to a place where they can be overridden privately

### PR DESCRIPTION
**Pull request by owocki**
Wrote this up last night.  Finally got around to submitting it as a PR.
# What

Moves NN / classifier trainers & trader information to a place where they can be overridden privately: `settings.py`.

This allows contributors to tune their own settings AND contribute back to the main fork without having to juggle a bunch of `git stash`s.

Note: also some linting in this PR.  Sorry, linter went crazy :P
# Why

See https://github.com/owocki/pytrader/issues/36
# img

### CODE REVIEW

**Comment by Snipa22** [comment]
Looks fine to me, the sooner we merge this in the better, as I'm still looking to take apart most of the NN system for breakout, so the more we change around it, the more difficult it'll end up being.

**Comment by t0mk** [comment]
Looks good to me.

**Comment by john-brunelle** [comment]
This is a test comment ☺️

**Comment by john-brunelle** [comment]
This is a test

**Comment by john-brunelle** [comment]
This is a test

**Comment by john-brunelle** [comment]
This is another test

**Comment by john-brunelle** [comment]
Test number 3

**Comment by john-brunelle** [comment]
Test number 4

**Comment by john-brunelle** [comment]
Test number 4

**Comment by john-brunelle** [comment]
Test number 5

**Comment by john-brunelle** [comment]
Test number 5

**Comment by john-brunelle** [comment]
Test 6

**Comment by john-brunelle** [comment]
Test 7

**Comment by john-brunelle** [comment]
Test 17

**Comment by john-brunelle** [comment]
Test 18

**Comment by john-brunelle** [comment]
Test 19

**Comment by john-brunelle** [comment]
Test 20

**Comment by john-brunelle** [comment]
Test 21

**Comment by john-brunelle** [comment]
Sadfsdf

**Comment by john-brunelle** [comment]
hello this is a test cmment

**Comment by darkdarkdragon** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__This issue now has a funding of 0.1 ETH (69.21 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/owocki/pytrader/59/606).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Pull request merged**
